src/frontend/__init__.py
from flask import Flask, render_template

from frontend.views import home, profile, summary, search

app = Flask(__name__)
app.config['SECRET_KEY'] = "A very secret key"


@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404


app.register_blueprint(home.home_bp)
app.register_blueprint(profile.profile_bp)
app.register_blueprint(summary.summary_bp)
app.register_blueprint(search.search_bp)

src/frontend/views/home.py
import pickle

from backend import Faculty
from config import config
from flask import Blueprint, render_template

home_bp = Blueprint('home_bp', __name__)

# get all objects
with open(config.SAVED_FILE, 'rb') as inp:
    s = pickle.load(inp)

db = Faculty()
db.extend(s)


@home_bp.route('/')
def homepage():
    '''
    creates a page to display all faculty members
    '''
    faculty_list = list(zip(db.faculty_list, db.links()))
    faculty_list = sorted(faculty_list, key=lambda x: x[0].name)
    return render_template('home.html', faculty_list=faculty_list)

src/frontend/views/processes/__init__.py
from .plot_ import Bar, Network, Scatter

src/frontend/views/profile.py
import pickle

from backend import Faculty
from config import config
from flask import Blueprint, render_template
from frontend.views.processes import Bar

profile_bp = Blueprint('profile_bp', __name__, url_prefix='/profile')
page = "profile"

# get all objects
with open(config.SAVED_FILE, 'rb') as inp:
    s = pickle.load(inp)

db = Faculty()
db.extend(s)


@profile_bp.route('/<name>')  # name has + for whitespace
def profile(name):
    '''
    creates a single profile page
    '''
    rname = name.replace("+", " ")
    f = db.get_member(rname)
    if f is None:
        return render_template("404.html")
    Bar(db).plot(page=page, faculty=f,
                 filename=config.FCITES_PATH,
                 xaxis_title="Year",
                 yaxis_title="No. of citations")
    return render_template("profile.html", faculty=f)


@profile_bp.route('/citesperyear')
def show_citeframe():
    '''
    render plotly saved html interactive graph
    in webpage
    '''
    return render_template('citesperyear.html')

src/frontend/views/search.py
import pickle

from backend import Faculty
from config import config
from flask import Blueprint, render_template, request
from flask_wtf import FlaskForm
from wtforms import SelectField, StringField, SubmitField
from wtforms.validators import DataRequired

search_bp = Blueprint('search_bp', __name__, url_prefix='/search')

# get all objects
with open(config.SAVED_FILE, 'rb') as inp:
    s = pickle.load(inp)

db = Faculty()
db.extend(s)

# can be
# 2018, 2022/ >1000
# 2013- 2017/ 900-4000
# 2013- 2017/ 900, 4000
# 2014/ <10
# 2014/ 400
CHOICES = [('Interests', 'Interests'),
           ('Grants', 'Grants'),
           ('Publications', 'Publications'),
           ('Citations', 'Citations - <year-range>/<citation-range>')]


class SearchForm(FlaskForm):
    """
    Search bar
    """
    select = SelectField(
        'Select query',
        choices=CHOICES
    )

    search = StringField(
        'Query',
        [DataRequired()]
    )
    submit = SubmitField("Search")


@search_bp.route('/', methods=("GET", "POST"))  # name has + for whitespace
# code referenced from: https://www.tutorialspoint.com/flask/flask_wtf.htm
def search():
    '''
    Search page
    '''
    form = SearchForm()
    if request.method == 'POST':
        if form.validate() is False:
            return render_template('404.html')
        else:
            selected = form.select.data
            query = form.search.data
            fc = db.find_all(selected, query)
            return render_template('search.html', form=form, fc=fc)
    elif request.method == 'GET':
        return render_template('search.html', form=form, fc=[])

src/frontend/views/summary.py
import json
import pickle

from backend import Faculty
from config import config
from flask import Blueprint, render_template, request, jsonify
from frontend.views.processes import Bar, Network, Scatter

summary_bp = Blueprint('summary_bp', __name__, url_prefix='/summary')

# get all objects
with open(config.SAVED_FILE, 'rb') as inp:
    s = pickle.load(inp)

db = Faculty()
db.extend(s)


@summary_bp.route("/")
def stats():
    '''
    summary page for stats containing:
    1. 2 Bars (total cites over years, count of interests)
    2. 1 Network (who worked with who on what reserach paper? NTU only)
    3. 2 Scatter (citations per publications, quality of paper vs grants)
    '''
    Bar(db).plot(page="summary",
                 filename=config.TOT_FCITES_PATH,
                 title="Cites per year",
                 xaxis_title="Year",
                 yaxis_title="No. of citations")
    Bar(db).plot(page="summary",
                 filename=config.TOT_FINTERESTS_PATH,
                 type="interests",
                 title="Interests",
                 xaxis_title="Count",
                 yaxis_title="Type",
                 height=1000,
                 width=1000,
                 bargap=0.2)
    # remove non NTU coauthors
    db.filter_authors()
    Network(db).plot(filename=config.NET_PATH, edge_dict=None,
                     **config.NETWORK_CONFIG)
    Scatter(db).plot(filename=config.SCATTER_PATH_TOTAL,
                     title_text="Lifetime citations of every faculty against publications",
                     xaxis_title="Number of publications",
                     yaxis_title="Lifetime citations earned",
                     x=db.publications,
                     y=db.citations,
                     text=db.faculty,
                     marker=dict(size=db.grants,
                                 sizemode='area',
                                 sizeref=2.*max(db.grants)/(40.**2),
                                 sizemin=10),
                     **config.SCATTER_CONFIG)
    Scatter(db).plot(filename=config.SCATTER_PATH_QUALITY,
                     title_text="Quality of paper against grants received",
                     xaxis_title="Number of grants",
                     yaxis_title="Quality of paper",
                     x=db.grants,
                     y=[i / j for i, j in zip(db.citations, db.publications)
                        if j != 0],
                     text=db.faculty,
                     **config.SCATTER_CONFIG)
    return render_template("summary.html", faculty_list=db)


@summary_bp.route("/recommend_me")
def recommend_me():
    '''
    recommends grants based on interest
    '''
    selected = request.values.get('interest_select')
    grants = db.recommend_grants(selected)
    return jsonify(grants)


@summary_bp.route("/total_cites")
def show_totalcites():
    '''
    renders total citations plot
    '''
    return render_template('summary_cites.html')


@summary_bp.route("/total_interests")
def show_totalinterests():
    '''
    renders total interests plot
    '''
    return render_template('summary_interests.html')


@summary_bp.route("/network")
def show_network():
    '''
    renders network
    '''
    return render_template('summary_network.html')


@summary_bp.route("/scatter_plot")
def show_scatter():
    '''
    renders bubble chart of citations per publications vs grants
    '''
    return render_template('summary_scatter.html')


@summary_bp.route("/scatter_plot_q")
def show_scatter_q():
    '''
    renders quality of papers scatter plot
    '''
    return render_template('summary_scatter_q.html')

src/frontend/templates/base.html
<!DOCTYPE html>
<head>

  <title>
    {% block title %}SCSE Faculty List{% endblock %}
  </title>

  <meta charset="UTF-8">
  <meta name="description" content="SCSE faculty and their information">
  <meta name="author" content="Kam Chin Voon">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{ url_for('static', filename='main_styles.css') }}">
  {% block html_head %}{% endblock %}

</head>

<body>
    <div class= "divider-space"></div>
    <img src="https://www.ntu.edu.sg/images/default-source/corporate/ntu_logo.png?sfvrsn=b5dd1d82_5" alt="NTU Logo" class="image" id="ntu-logo">
    <div class= "divider-space"></div>
    <!-- Top navigation -->
    {% set navigation_bar = [
                                ('/', 'home', 'Home'),
                                ('/summary/', 'summary', 'Summary'),
                                ('/search/', 'search', 'Search')
                            ] -%}
    {% set active_page = active_page|default('home') -%}
    <ul class="navigation" id="home-navigation">
      {% for href, id, caption in navigation_bar %}
      <a {% if id == active_page %} class="active"{% endif %} href="{{ href|e }}">{{ caption|e }}</a>
      {% endfor %}
    </ul>
  
    <div id="content">
      {% block content %}{% endblock %}
    </div>

</body>
<footer>
  <p>Author: Kam Chin Voon</p>
  <p><a href="https://www.youtube.com/watch?v=BBJa32lCaaY">Email</a></p>
</footer>

src/frontend/templates/home.html
{% extends "base.html" %}
{% set active_page = "home" %}
{% block content %}
    <table id="table faculty-list">
      <caption>
        List of faculty members
      </caption>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      {% for member, link in faculty_list%}
        <tr>
          <td><a href={{ link }}>{{ member['name'] }}</a></td>
          <td>{{ member['email'] }}</td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
{% endblock %}

src/frontend/templates/profile.html
{% extends "base.html" %}

{% block content %}
    <p class="navigation"> Quick navigation <span>&#128640;</span></p>
    <ul class="navigation" id="profile-navigation">
        <a href="#biography">Biography</a>
        <a href="#interests">Interests</a>
        <a href="#grants">Grants</a>
        <a href="#pub">Publications</a>
        <a href="#citesperyear-graph">Statistics</a>
    </ul>
    
    <div class="profile-details">
        <h1>{{ faculty.name }}</h1>
        <img class="faculty-img" src={{ faculty.urlpicture }} alt="Image of faculty member"/>
    </div>

    <div class="faculty-links">
        <h2 id= "header-links"><u>Useful Links:</u></h2>
        <a href={{ faculty.drntu }}><p>DR NTU</p></a>
        <a href={{ faculty.dblp }}><p>DBLP</p></a>
    </div>

    <div id="biography">
        <div class="float-container">
            <div class="side-by-side-info">
                <h2 class="heading">Biography</h2>
            </div>
            <div class="side-by-side-info">
                <p class="info">
                {{ (faculty.biography) | wordwrap(48)}}
                </p>
            </div>
        </div>
    </div>

    <div id="interests">
        <div class="float-container">
            <div class="side-by-side-info">
                <h2 class="heading">Interests</h2>
            </div>
            <div class="side-by-side-info">
                <p class="info">
                    <ul>
                        {% for interest in faculty.interests %}
                            <li>{{ interest }}</li>
                        {% endfor %}
                        </ul>
                </p>
            </div>
        </div>
    </div>

    <div id="grants">
        <div class="float-container">
            <div class="side-by-side-info">
                <h2 class="heading">Current grants</h2>
            </div>
            <div class="side-by-side-info">
                <p class="info">
                    <ul>
                        {% for grant in faculty.grants %}
                            <li>{{ grant }}</li>
                        {% endfor %}
                    </ul>
                </p>
            </div>
        </div>
    </div>

    <div id="pub">
        <div class="float-container">
            <div class="side-by-side-info">
                <h2 class="heading">Publications</h2>
            </div>
            <div class="side-by-side-info">
                <p class="info">
                    <table class="table faculty-publications">
                        <thead>
                        <tr>
                            <th>Publication name</th>
                            <th>Year of publish</th>
                            <th>No. citations</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for pub in faculty.publications %}
                            <tr>
                            <td>{{ pub[0] }}</td>
                            <td>{{ pub[1] }}</td>
                            <td>{{ pub[2] }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </p>
            </div>
        </div>
    </div>

    <div id="citesperyear-graph">
        <div class="float-container">
            <div class="side-by-side-info">
                <h2 class="heading">Graph of citations per year</h2>
            </div>
            <div class="side-by-side-info">
                <p class="info">
                    <iframe style="width: 100%;border:3px solid black; " src="{{ url_for('profile_bp.show_citeframe') }}" height="800" id="cites-graph"></iframe>
                    <!--iframe tag-->
                  
                    <script>
                        // Selecting the iframe element
                        var frame = document.getElementById("cites-graph");
                        
                        // Adjusting the iframe height onload event
                        frame.onload = function()
                        // function execute while load the iframe
                        {
                        // set the height of the iframe as 
                        // the height of the iframe content
                        frame.style.height = 
                        frame.contentWindow.document.body.scrollHeight + 'px';
                        
                
                        // set the width of the iframe as the 
                        // width of the iframe content
                        frame.style.width  = 
                        frame.contentWindow.document.body.scrollWidth+'px';
                            
                        }
                        function scrollTo() {
                            selectElement = document.querySelector('#navi');
                            output = selectElement.value;
                            document.getElementById(output).scrollIntoView();
                        }
                        </script>
                </p>
            </div>
        </div>
    </div>

{% endblock %}

src/frontend/templates/search.html
{% extends "base.html" %}

{% block content %}
<form action="{{ url_for('search_bp.search') }}" method="POST">
    {{ form.csrf_token }}
    

    <p>
        {{ form.select.label }}
        {{ form.select() }}
    </p>


    <p>
        {{ form.search.label }}
        {{ form.search() }}
    </p>

    <p>
        {{ form.submit() }}
    </p>
</form>
<span>Showing {{ fc|length }} results</span>
<h2>
    You searched in {{ form.select.data }} for {{ form.search.data }}
</h2>
<table id="table search-results">
  <thead>
    <tr>
      <th>No.</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    {% for f in fc %}
      <tr>
        <td>{{ loop.index0 + 1 }}</td>
        <td><a href={{ f.link }}>{{ f.name }}</a></td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
{% endblock %}

src/frontend/templates/summary.html
{% extends "base.html" %}
{% block content %}
<div id="cites-graph">
    <div class="graphs">
        <h2>Cites per year graph</h2>
        <iframe src="{{ url_for('summary_bp.show_totalcites') }}"></iframe>
    </div>
</div>

<div id="interest-graph">
    <div class="graphs">
        <h2>Interests of faculty</h2>
        <iframe src="{{ url_for('summary_bp.show_totalinterests') }}"></iframe>
    </div>
</div>

<div id="network-graph">
    <div class="graphs">
        <h2>Network graph</h2>
        <iframe src="{{ url_for('summary_bp.show_network') }}" align="center"></iframe>
    </div>
</div>

<div id="scatter-graph">
    <div class="graphs">
        <h2>Bubble chart</h2>
        <div class="left">
            <iframe src="{{ url_for('summary_bp.show_scatter') }}" align="left"></iframe>
        </div>
        <div class="right">
            <iframe src="{{ url_for('summary_bp.show_scatter_q') }}" align="right"></iframe>
        </div>
    </div>
</div>
<div class="explanation">
    Above graph shows the number of publications vs citations each member of the faculty has. The area of the bubble represents the number of grants the faculty has. 
</div>
<!-- referred from https://stackoverflow.com/a/32020159-->
<form class="form-inline" method="GET" action="{{ url_for('summary_bp.recommend_me') }}">
    <h2>Recommend grants based on interest</h2>
    <div class="form-group">
      <div class="input-group">
          <span class="input-group-addon">Please select your interest</span>
              <select name="interest_select" class="selectpicker form-control">
                {% for i in faculty_list.interests %}
                <option value="{{ i }}">{{ i }}</option>
                {% endfor %}
              </select>
          <button type="submit" class="btn btn-default">Go</button>
      </div>
      
    </div>
  </form>
{% endblock %}